"use client";

import Link from "next/link";
import React, { useState, useRef, useEffect } from "react";

interface HeadingItem {
  level: number;
  text: string;
  slug: string;
}

interface TableOfContentsProps {
  content: string;
}

/*
  This Component was mostly generated by AI, with some manual tweaks to improve functionality and styling.
  TODO: Redo it manually to have more control and cleaner code.
*/

function TableOfContents({ content }: TableOfContentsProps) {
  const scrollContainerRef = useRef<HTMLDivElement>(null);
  const [showTopFade, setShowTopFade] = useState(false);
  const [showBottomFade, setShowBottomFade] = useState(false);
  const [activeHeading, setActiveHeading] = useState<string>("");
  const isUserScrollingRef = useRef(false);

  // Extract headings from markdown content
  const extractHeadings = (markdownContent: string): HeadingItem[] => {
    // Split content into lines to process line by line
    const lines = markdownContent.split("\n");
    const headings: HeadingItem[] = [];
    let inCodeBlock = false;
    let codeBlockDelimiter = "";

    // Process each line to find headings while avoiding code blocks
    for (const line of lines) {
      // Check for start/end of fenced code blocks (``` or ~~~ with optional content)
      const codeBlockMatch = line.match(/^(```+|~~~+)/);
      if (codeBlockMatch) {
        if (!inCodeBlock) {
          // Starting a code block
          inCodeBlock = true;
          codeBlockDelimiter = codeBlockMatch[1];
        } else if (line.startsWith(codeBlockDelimiter)) {
          // Ending a code block (must match the opening delimiter)
          inCodeBlock = false;
          codeBlockDelimiter = "";
        }
        continue; // Skip the code block delimiter line
      }

      // If we're in a code block, skip this line entirely
      if (inCodeBlock) {
        continue;
      }

      // Check if this line is a heading (only process lines outside code blocks)
      const headingMatch = line.match(/^(#{1,6})\s+(.+)$/);
      if (headingMatch) {
        const level = headingMatch[1].length;
        let text = headingMatch[2].trim();

        // Remove markdown formatting from heading text
        text = text
          .replace(/\*\*(.*?)\*\*/g, "$1") // Remove bold
          .replace(/\*(.*?)\*/g, "$1") // Remove italic
          .replace(/`(.*?)`/g, "$1") // Remove inline code
          .replace(/\[(.*?)\]\(.*?\)/g, "$1") // Remove links, keep text
          .trim();

        // Create slug similar to rehype-slug
        const slug = text
          .toLowerCase()
          .replace(/[^\w\s-]/g, "") // Remove special characters
          .replace(/\s+/g, "-") // Replace spaces with hyphens
          .replace(/^-+|-+$/g, "") // Remove leading/trailing hyphens
          .trim();

        if (text && slug) {
          headings.push({ level, text, slug });
        }
      }
    }

    return headings;
  };

  const headings = extractHeadings(content);

  // Track active heading using intersection observer
  useEffect(() => {
    const headingElements: { [key: string]: Element } = {};

    // Find all heading elements in the document
    headings.forEach(({ slug }) => {
      const element = document.getElementById(slug);
      if (element) {
        headingElements[slug] = element;
      }
    });

    if (Object.keys(headingElements).length === 0) return;

    const findClosestHeading = () => {
      // Don't update if user just clicked a TOC link
      if (isUserScrollingRef.current) return;

      let closestHeading = "";
      let closestDistance = Infinity;
      const viewportCenter = window.innerHeight / 2;

      // Find the heading closest to the center of viewport
      Object.entries(headingElements).forEach(([slug, element]) => {
        const rect = element.getBoundingClientRect();
        const elementCenter = rect.top + rect.height / 2;
        const distanceFromCenter = Math.abs(elementCenter - viewportCenter);

        // Prefer headings that are visible and closer to center
        if (rect.top < window.innerHeight && rect.bottom > 0) {
          if (distanceFromCenter < closestDistance) {
            closestDistance = distanceFromCenter;
            closestHeading = slug;
          }
        }
      });

      // If no heading is in viewport, find the one closest to the top
      if (!closestHeading) {
        Object.entries(headingElements).forEach(([slug, element]) => {
          const rect = element.getBoundingClientRect();
          const distanceFromTop = Math.abs(rect.top);

          if (distanceFromTop < closestDistance) {
            closestDistance = distanceFromTop;
            closestHeading = slug;
          }
        });
      }

      if (closestHeading && closestHeading !== activeHeading) {
        setActiveHeading(closestHeading);
      }
    };

    // Create intersection observer for performance
    const observer = new IntersectionObserver(
      (entries) => {
        // Only update when headings enter or leave viewport
        const hasVisibleHeading = entries.some((entry) => entry.isIntersecting);
        if (hasVisibleHeading) {
          findClosestHeading();
        }
      },
      {
        rootMargin: "-10% 0% -10% 0%",
        threshold: 0,
      }
    );

    // Observe all headings
    Object.values(headingElements).forEach((element) => {
      observer.observe(element);
    });

    // Also listen to scroll for smooth updates
    let ticking = false;
    const handleScroll = () => {
      if (!ticking) {
        requestAnimationFrame(() => {
          findClosestHeading();
          ticking = false;
        });
        ticking = true;
      }
    };

    window.addEventListener("scroll", handleScroll, { passive: true });

    // Set initial active heading
    findClosestHeading();

    // Cleanup
    return () => {
      observer.disconnect();
      window.removeEventListener("scroll", handleScroll);
    };
  }, [headings, activeHeading]);

  // Handle TOC link clicks
  const handleTocClick = (targetSlug: string) => {
    // Immediately set the active heading to the clicked one
    setActiveHeading(targetSlug);

    // Disable automatic scroll tracking temporarily
    isUserScrollingRef.current = true;

    // Re-enable scroll tracking after scroll completes
    setTimeout(() => {
      isUserScrollingRef.current = false;
    }, 1000); // Give enough time for smooth scrolling to complete
  };

  // Handle scroll to show/hide fade effects
  const handleScroll = () => {
    if (!scrollContainerRef.current) return;

    const { scrollTop, scrollHeight, clientHeight } =
      scrollContainerRef.current;

    // Show top fade if scrolled down
    setShowTopFade(scrollTop > 10);

    // Show bottom fade if not scrolled to bottom
    setShowBottomFade(scrollTop + clientHeight < scrollHeight - 10);
  };

  // Check initial state and set up scroll listener
  useEffect(() => {
    const container = scrollContainerRef.current;
    if (!container) return;

    // Check initial state
    handleScroll();

    container.addEventListener("scroll", handleScroll);
    return () => container.removeEventListener("scroll", handleScroll);
  }, [headings]);

  // Don't render TOC if there are no headings
  if (headings.length === 0) {
    return null;
  }

  return (
    <nav className="sticky top-10 col-start-3 row-span-1 ml-10 mr-auto hidden h-[calc(100vh-5.5rem)] max-w-md xl:block">
      {/* Top fade overlay */}
      <div
        className={`absolute top-0 left-0 right-0 h-12 bg-gradient-to-b from-background via-background/80 to-transparent pointer-events-none z-10 transition-opacity duration-300 ${
          showTopFade ? "opacity-100" : "opacity-0"
        }`}
      />

      {/* Scrollable content */}
      <div ref={scrollContainerRef} className="overflow-y-auto h-full">
        <ul className="p-0 m-0 space-y-1 px-4 py-4 list-disc">
          {/* <p className="px-4 mb-2 mt-1 font-medium">On this page</p> */}
          {headings.map((heading, index) => (
            <li
              key={index}
              style={{
                listStyleType: "initial",
              }}
              className="flex items-center"
            >
              <Link
                href={`#${heading.slug}`}
                onClick={() => handleTocClick(heading.slug)}
                className={`w-full text-sm transition-all duration-200 block py-1.5 px-2 rounded ${
                  activeHeading === heading.slug
                    ? "text-foreground bg-accent/50"
                    : "text-muted-foreground hover:text-foreground hover:bg-accent/25"
                }`}
                style={{
                  paddingLeft: `${(heading.level - 1) * 18 + 12}px`,
                }}
              >
                {heading.text}
              </Link>
            </li>
          ))}
        </ul>
      </div>

      {/* Bottom fade overlay */}
      <div
        className={`absolute bottom-0 left-0 right-0 h-12 bg-gradient-to-t from-background via-background/80 to-transparent pointer-events-none z-10 transition-opacity duration-300 ${
          showBottomFade ? "opacity-100" : "opacity-0"
        }`}
      />
    </nav>
  );
}

export default TableOfContents;
