import type { Metadata } from "next";
import { Roboto, Roboto_Mono } from "next/font/google";
import "./assets/globals.css";
import { ThemeProvider } from "next-themes";
import { Navbar } from "../components/layout/navbar";
import Footer from "@/components/layout/footer";
import Content from "@/components/layout/content";
import { ServerStatus } from "@/components/layout/server-status";

const robotoSans = Roboto({
  variable: "--font-roboto-sans",
  subsets: ["latin"],
});

const robotoMono = Roboto_Mono({
  variable: "--font-roboto-mono",
  subsets: ["latin"],
});

export const metadata: Metadata = {
  title: "Create Next App",
  description: "Generated by create next app",
};

export default function RootLayout({
  children,
}: Readonly<{
  children: React.ReactNode;
}>) {
  return (
    <html lang="en" suppressHydrationWarning>
      <body
        className={`${robotoSans.variable} ${robotoMono.variable} antialiased min-h-screen flex flex-col justify-between items-center`}
      >
        <ThemeProvider
          attribute="class"
          defaultTheme="system"
          enableSystem
          disableTransitionOnChange
        >
          <Navbar />
          <Content>{children}</Content>
          <Footer />
          <ServerStatus />
        </ThemeProvider>
      </body>
    </html>
  );
}
