"use client";

import Link from "next/link";
import React, { useState, useRef, useEffect } from "react";

interface HeadingItem {
  level: number;
  text: string;
  slug: string;
}

function TableOfContents() {
  const scrollContainerRef = useRef<HTMLDivElement>(null);
  const [activeHeading, setActiveHeading] = useState<string>("");
  const [headings, setHeadings] = useState<HeadingItem[]>([]);
  const isUserScrollingRef = useRef(false);

  // Extract headings from the actual DOM after MDX rendering
  const extractHeadingsFromDOM = (): HeadingItem[] => {
    const headingElements = document.querySelectorAll("h1, h2, h3, h4, h5, h6");
    const headings: HeadingItem[] = [];

    headingElements.forEach((element) => {
      const level = parseInt(element.tagName[1]);
      const text = element.textContent || "";
      const slug = element.id; // Use the actual ID generated by rehype-slug

      if (text && slug) {
        headings.push({ level, text, slug });
      }
    });

    return headings;
  };

  // Extract headings on mount and when content changes
  useEffect(() => {
    const extractedHeadings = extractHeadingsFromDOM();
    setHeadings(extractedHeadings);

    // Re-extract if DOM changes (for dynamic content)
    const observer = new MutationObserver(() => {
      const newHeadings = extractHeadingsFromDOM();
      setHeadings(newHeadings);
    });

    observer.observe(document.body, {
      childList: true,
      subtree: true,
    });

    return () => observer.disconnect();
  }, []);

  // Track active heading using intersection observer
  useEffect(() => {
    if (headings.length === 0) return;

    const headingElements: { [key: string]: Element } = {};

    // Find all heading elements in the document
    headings.forEach(({ slug }) => {
      const element = document.getElementById(slug);
      if (element) {
        headingElements[slug] = element;
      }
    });

    if (Object.keys(headingElements).length === 0) return;

    const findClosestHeading = () => {
      if (isUserScrollingRef.current) return;

      let closestHeading = "";
      let closestDistance = Infinity;
      const viewportCenter = window.innerHeight / 2;

      Object.entries(headingElements).forEach(([slug, element]) => {
        const rect = element.getBoundingClientRect();
        const elementCenter = rect.top + rect.height / 2;
        const distanceFromCenter = Math.abs(elementCenter - viewportCenter);

        if (rect.top < window.innerHeight && rect.bottom > 0) {
          if (distanceFromCenter < closestDistance) {
            closestDistance = distanceFromCenter;
            closestHeading = slug;
          }
        }
      });

      if (!closestHeading) {
        Object.entries(headingElements).forEach(([slug, element]) => {
          const rect = element.getBoundingClientRect();
          const distanceFromTop = Math.abs(rect.top);

          if (distanceFromTop < closestDistance) {
            closestDistance = distanceFromTop;
            closestHeading = slug;
          }
        });
      }

      if (closestHeading && closestHeading !== activeHeading) {
        setActiveHeading(closestHeading);
      }
    };

    const observer = new IntersectionObserver(
      (entries) => {
        const hasVisibleHeading = entries.some((entry) => entry.isIntersecting);
        if (hasVisibleHeading) {
          findClosestHeading();
        }
      },
      {
        rootMargin: "-10% 0% -10% 0%",
        threshold: 0,
      }
    );

    Object.values(headingElements).forEach((element) => {
      observer.observe(element);
    });

    let ticking = false;
    const handleScroll = () => {
      if (!ticking) {
        requestAnimationFrame(() => {
          findClosestHeading();
          ticking = false;
        });
        ticking = true;
      }
    };

    window.addEventListener("scroll", handleScroll, { passive: true });
    findClosestHeading();

    return () => {
      observer.disconnect();
      window.removeEventListener("scroll", handleScroll);
    };
  }, [headings, activeHeading]);

  const handleTocClick = (targetSlug: string) => {
    setActiveHeading(targetSlug);
    isUserScrollingRef.current = true;
    setTimeout(() => {
      isUserScrollingRef.current = false;
    }, 500);
  };

  if (headings.length === 0) {
    return null;
  }

  // Find the minimum level to adjust padding
  const minLevel = Math.min(...headings.map((h) => h.level));

  return (
    <nav className="sticky top-10 col-start-3 row-span-1 ml-10 mr-auto hidden h-[calc(100vh-5.5rem)] max-w-md xl:block overflow-y-scroll pe-4">
      <p className="font-medium mb-2">On this page</p>
      <div
        ref={scrollContainerRef}
        className="overflow-y-auto"
        style={{ scrollbarWidth: "thin" }}
      >
        <ul className="p-0 m-0 space-y-1 list-disc">
          {headings.map((heading, index) => (
            <li
              key={`${heading.slug}-${index}`}
              style={{ listStyleType: "initial" }}
              className="flex items-center"
            >
              <Link
                href={`#${heading.slug}`}
                onClick={() => handleTocClick(heading.slug)}
                className={`w-full text-sm transition-all duration-200 block py-1.5 rounded ${
                  activeHeading === heading.slug
                    ? "text-blue-400"
                    : "text-muted-foreground hover:text-foreground"
                }`}
                style={{
                  paddingLeft: `${(heading.level - minLevel) * 18}px`,
                }}
              >
                {heading.text}
              </Link>
            </li>
          ))}
        </ul>
      </div>
      <hr className="my-6" />
    </nav>
  );
}

export default TableOfContents;
